#ifndef CONSTANTS_H
#define CONSTANTS_H

extern const int WIDTH, HEIGHT, FPS,
SPHERE_RINGS, SPHERE_SLICES;

extern const float SCALE, SCALE_OBJECTS, CAMERA_SPEED, CAMERA_ACCELERATION, CAMERA_SLOWDOWN, DELTA_TIME, AU;

extern const double G;

#endif